name: Deploy Storybook

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Storybook 🔧
        run: yarn build-storybook

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './storybook-static/'

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
